apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-member
  template:
    metadata:
      labels:
        app: msa-member
    spec:
      containers:
      - name: msa-member
        image: jekim12/msa-member:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: msa-member-svc
spec:
  selector:
    app: msa-member
  ports:
  - port: 80
    targetPort: 8080
  selector:
      app: msa-member
