# msa-member Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-member
  template:
    metadata:
      labels:
        app: msa-member
    spec:
      containers:
        - name: msa-member
          image: suhyen/msa-member:v2
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: member-secret
                  key: mysql-url
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: member-secret
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: member-secret
                  key: mysql-password
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: member-secret
                  key: email-username
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: member-secret
                  key: email-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: member-secret
                  key: jwt-secret