# msa-member Service
apiVersion: v1
kind: Service
metadata:
  name: member-service
spec:
  selector:
    app: msa-member
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP